app/controllers/meal_plans_controller.rb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/index.html.erb
app/views/simple_calendar/_month_calendar.html.erb
config/routes.rb

献立表のカレンダー表示画面を作成

---

app/views/layouts/application.html.erb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/_meal.html.erb
app/views/meal_plans/_meal_plan.html.erb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/edit.html.erb
app/views/meal_plans/index.html.erb
app/views/meal_plans/show.html.erb
app/views/simple_calendar/_month_calendar.html.erb
app/views/simple_calendar/_week_calendar.html.erb

カレンダー表示とヘッダーにクラス名を追加

---

.github/workflows/ci.yml
.rubocop.yml
Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/helpers/meal_plans_helper.rb
app/views/meal_plans/_form.html.erb
app/views/simple_calendar/_week_calendar.html.erb
spec/factories/meal_plans.rb
spec/factories/meals.rb
spec/rails_helper.rb
spec/support/capybara.rb
spec/support/login_support.rb
spec/system/meal_plans_spec.rb

MealPlanのシステムテストを追加

---

app/views/meal_plans/index.html.erb
app/views/meals/new.html.erb

timingでソートしたいmealsの部分を全部meals_sort_by_timingに修正

---

app/controllers/meal_plans_controller.rb
app/helpers/meal_plans_helper.rb
app/helpers/meals_helper.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/_meal_plan.html.erb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/edit.html.erb
app/views/meal_plans/index.html.erb
app/views/meal_plans/new.html.erb
app/views/meal_plans/show.html.erb
app/views/meals/_meal.html.erb
spec/system/meal_plans_spec.rb

献立表部分にturbo-frameを追加

---

app/controllers/remarks_controller.rb
app/views/meals/new.html.erb
app/views/meeting_rooms/show.html.erb
app/views/remarks/_form.html.erb
app/views/remarks/_remark.html.erb
app/views/remarks/create.turbo_stream.erb
app/views/remarks/destroy.turbo_stream.erb

相談部屋をturbo化した

---

app/controllers/meal_plans_controller.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/_meal_plan.html.erb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/edit.html.erb
app/views/meal_plans/index.html.erb
app/views/meal_plans/new.html.erb
app/views/meal_plans/show.html.erb
app/views/meals/_meal.html.erb
app/views/meals/new.html.erb
app/views/meeting_rooms/show.html.erb
app/views/remarks/_remark.html.erb
app/views/simple_calendar/_month_calendar.html.erb
app/views/simple_calendar/_week_calendar.html.erb
config/application.rb
config/locales/ja.yml
spec/system/meal_plans_spec.rb

日本語表記に変更した

---

.erb-lint.yml
.github/workflows/ci.yml
app/assets/stylesheets/application.css
app/javascript/controllers/dropdown_controller.js
app/views/shared/_header.html.erb
app/views/shared/_menu.html.erb
app/views/simple_calendar/_week_calendar.html.erb
config/importmap.rb
config/locales/ja.yml
vendor/javascript/@fortawesome--fontawesome-free.js
vendor/javascript/@hotwired--stimulus.js
vendor/javascript/tailwindcss-stimulus-components.js

ハンバーガーメニューを作成

---

config/routes.rb

session部分のルーティングが重複していたので削除した。

ルーティングの重複を修正

---

.rubocop.yml
app/assets/stylesheets/application.css
app/controllers/meal_plans_controller.rb
app/controllers/meeting_rooms_controller.rb
app/controllers/remarks_controller.rb
app/controllers/users_controller.rb
app/models/meal.rb
app/models/meal_plan.rb
app/models/remark.rb
app/models/user.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/_meal_plan.html.erb
app/views/meals/_timing_form.html.erb
app/views/meals/new.html.erb
app/views/meeting_rooms/show.html.erb
app/views/remarks/_comment.html.erb
app/views/remarks/_form.html.erb
app/views/remarks/create.turbo_stream.erb
app/views/users/edit.html.erb
spec/factories/meal_plans.rb
spec/system/meal_plans_spec.rb

- #110
- 概要
- MealPlanがcreate時Mealのname1つ以上持つようにバリデーション設定
（MeetingRoom作成時はバリデーションスキップ）
- Remarkのcontentが未入力の時にバリデーション
- Userのnameが未入力、20文字以上の時にバリデーション

エラーメッセージを表示するようにした

---

Gemfile
Gemfile.lock
app/controllers/remarks_controller.rb
app/models/remark.rb
app/views/meeting_rooms/show.html.erb
app/views/remarks/_comment.html.erb
app/views/remarks/_edit_link.html.erb
app/views/remarks/_proposal.html.erb
app/views/remarks/create.turbo_stream.erb
app/views/remarks/update.turbo_stream.erb
config/cable.yml

- #109
Remarkの追加、更新、削除をリアルタイム通信にした

MeetingRoomをリアルタイム通信にした

---

app/views/meal_plans/_form.html.erb

formのtiming部分を以前の修正に合わせて修正した

---

app/javascript/controllers/clipboard_controller.js
app/views/families/show.html.erb

- #138 
scriptをベタ書きしていたのをstimulusを使用し書き換えた

URLコピーボタンを修正

---

app/controllers/meeting_rooms_controller.rb
app/controllers/remarks_controller.rb
app/models/remark.rb
app/views/meeting_rooms/show.html.erb
app/views/remarks/_comments.html.erb
app/views/remarks/_edit_link.html.erb
app/views/remarks/_proposal.html.erb
app/views/remarks/_proposals.html.erb
app/views/remarks/destroy.turbo_stream.erb
app/views/remarks/edit.html.erb
app/views/remarks/new.html.erb

- #112 
不具合が多かったのでremarkのedit_linkは全てに表示することとした

提案やコメントがない時にメッセージを表示するようにした

---

app/views/meal_plans/_meal_plan.html.erb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/index.html.erb
app/views/remarks/_comment.html.erb
app/views/remarks/_edit_link.html.erb
app/views/remarks/_proposal.html.erb
spec/system/meal_plans_spec.rb

提案・コメントのeditリンクを修正

---

app/helpers/meal_plans_helper.rb
app/views/meal_plans/_form.html.erb

MealPlanのsubmitボタンの表記のずれを修正

---

app/helpers/meal_plans_helper.rb
app/models/meal_plan.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/_meal_plan.html.erb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/index.html.erb
app/views/meals/_registered_meals.html.erb
spec/factories/meal_plans.rb
spec/factories/meals.rb
spec/models/meal_plan_spec.rb
spec/system/meal_plans_spec.rb

MealPlanのモデルテストとシステムテストを追加

---

.github/workflows/fly-deploy.yml

fly-deploy.ymlを再度修正

---

.github/workflows/fly-deploy.yml

fly-deploy.ymlを修正 3回目

---

app/views/meal_plans/_delete_button.html.erb
app/views/meal_plans/edit.html.erb
app/views/meal_plans/show.html.erb
spec/system/meal_plans_spec.rb

献立を削除する際に確認ダイアログを表示

---

.gitignore
Gemfile
Gemfile.lock
spec/spec_helper.rb

テストカバレッジを確認するためにgemのSimpleCovを追加

SimpleCovを追加

---

app/models/user.rb
spec/factories/users.rb
spec/models/user_spec.rb

Userのモデルテストを修正

---

db/seeds.rb

mealsが削除されててもseedを読み込めば必要数追加されるようにした
[skip ci]

seedデータを修正した

---

app/channels/connect_meeting_room_channel.rb
app/javascript/controllers/cable_connection_controller.js
app/views/meals/new.html.erb
app/views/meeting_rooms/show.html.erb
app/views/remarks/_form.html.erb
config/environments/test.rb
config/importmap.rb
spec/models/remark_spec.rb
spec/system/remarks_spec.rb

- モデルテストを追加
- システムテストを追加
- WebSocketと接続したらMeetingRoomの表示するように実装
- WebSocketと接続する前にテストが進んでbroadcastでの表示がでないことがあったため

Remarkのテストを追加

---

spec/system/meeting_rooms_spec.rb

MeetingRoomのテストを追加

---

app/controllers/meals_controller.rb
app/views/families/show.html.erb
app/views/home/index.html.erb
app/views/shared/_menu.html.erb
spec/models/family_spec.rb
spec/system/families_spec.rb
spec/system/home_spec.rb
spec/system/meals_spec.rb
spec/system/sessions_spec.rb

- Familyテストを追加
- ログインログアウトのテストを追加
- #71 
- 利用規約、プライバシーポリシー、使い方のテストを追加
- Mealの足りなかったテストを追加

足りないテストを追加した

---

app/javascript/controllers/dropdown_controller.js
app/javascript/controllers/flash_controller.js
app/javascript/controllers/modal_controller.js
app/views/meal_plans/show.html.erb

brakemanのwarningとconsoleのerrorを修正

---

Gemfile
Gemfile.lock
app/controllers/meal_plans_controller.rb
app/controllers/meeting_rooms_controller.rb

bulletを導入、N+1への対応をした

---

db/seeds.rb

seedデータの重複を修正

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/views/shared/_menu.html.erb

- current_userのfindをfind_byへ修正
- ログアウトリンクがturboにprefetchされないように設定
https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover
https://techracho.bpsinc.jp/hachi8833/2024_09_25/143750

session部分を修正

---

app/views/layouts/_header.html.erb
spec/system/users_spec.rb

userのシステムテストを追加

---

app/helpers/application_helper.rb
app/helpers/meal_plans_helper.rb
app/helpers/meals_helper.rb
app/helpers/meeting_rooms_helper.rb
app/helpers/sessions_helper.rb
app/helpers/simple_calendar_helper.rb
app/models/meal.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/_meal_plan.html.erb
app/views/meal_plans/calendar.html.erb
app/views/meal_plans/index.html.erb
app/views/meals/_meal.html.erb
app/views/meals/_registered_meals.html.erb
app/views/remarks/_comment.html.erb
spec/factories/meal_plans.rb
spec/helpers/application_helper_spec.rb
spec/helpers/home_helper_spec.rb
spec/helpers/meal_plans_helper_spec.rb
spec/helpers/meals_helper_spec.rb
spec/helpers/remarks_helper_spec.rb
spec/helpers/simple_calendar_helper_spec.rb
spec/models/meal_spec.rb
spec/rails_helper.rb

helperのテストを作成

---

app/models/meal.rb
app/models/meal_plan.rb
app/models/remark.rb
config/application.rb
config/locales/ja.yml
db/migrate/20241122050917_add_limit_to_meals.rb
db/migrate/20241122054752_add_limit_to_remarks.rb
db/schema.rb
spec/system/meal_plans_spec.rb
spec/system/remarks_spec.rb

- #204 
以下の項目に追加
- Meal
- name
- memo
- Remark
- content

入力に文字数制限を追加

---

README.md

READMEを書き足した

---

LICENSE.md

MIT Licenseを追加

---

README.md

READMEにseedデータ入りの献立表へのログインについて追加記載

---

app/javascript/controllers/dropdown_controller.js
app/javascript/controllers/flash_controller.js
app/javascript/controllers/modal_controller.js
app/views/layouts/_menu.html.erb

jsのcontroller内の余分な記述を削除、menuの修正

---

app/assets/stylesheets/application.css
app/views/meals/_timing_form.html.erb
app/views/meals/new.html.erb
spec/system/meals_spec.rb

提案を献立に登録するページのレイアウトの修正

---

app/views/home/index.html.erb

@motohiro-mm 
トップページにTailwindを使ったラジオボタンのサンプルを置きました。
結構複雑なコードになってるので、これをそのまま使うのがいいかもです（色などは調整してください）。

topページにラジオボタンのサンプルを置いた

---

config/importmap.rb

import先を変更

---

app/views/remarks/_comment.html.erb

コメントにユーザーの名前を表示
